name: Pull Request Review

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  review:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for Pull Request Review
        uses: reviewdog/wait-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge Pull Request
        run: echo "Perform the merge here"
